---
author: Ariane Lim
date: "2020-08-25"
description: I made a game about a bouncing steamed bun with C# and Unity. (WARNING! This video has sound that plays automatically.)
displayInList: true
displayInMenu: false
draft: false
dropCap: true
resources:
- name: featuredImage
  src: bouncybao1.png
categories:
  - Gaming
tags:
  - Unity
  - games
  - programming
title: Hello, Bouncy Bao!
---

The COVID lockdown here in Manila has led me to revisit some childhood "dreams" that I thought were too silly or unattainable for me to achieve. One of those dreams was to be a game designer.

So I bought a $11.99 course on udemy.com (Amazing course, BTW. Can't recommend it enough. Get it [HERE!](https://www.udemy.com/share/101WjsAkIddllVQXo=/) ), and I started programming away! 

With the combination of my digital drawing skills, good instructors from udemy.com and Unity, I'm ready to unveil my first ever video game! I had so much fun designing the whole set, working on the graphics, looking for the music, and etc. This whole ordeal has taught me to have a deeper appreciation to game developers who make these games for our entertainment.

Hopefully, I get good enough at this hobby to make meaningful games of my own. But for now, the simple gameplay and message of Bouncy Bao will have to do.

The mechanics of the game are simple:
Break the blocks to help Bouncy Bao transform himself into a new snack. Move the bamboo steamer using your mouse to make Bouncy Bao bounce and break the blocks.

Play it here:

<iframe src="https://i.simmer.io/@ariane_lim/bouncy-bao" style="width:600px;height:500px;border:0"></iframe>

<h5> For the love of social science, <h5><br>
<h5>Ariane</h5>

